[tool.towncrier]
    package = "apolo_cli"
    package_dir = "apolo-cli"
    directory = "CHANGELOG.D"
    filename = "CHANGELOG.md"
    name = "Apolo SDK/CLI"
    issue_format = "[#{issue}](https://github.com/neuro-inc/neuro-cli/issues/{issue})"
    start_string = "[comment]: # (towncrier release notes start)\n"
