trigger:
  batch: false
  tags:
    include:
    - v*
pr: none


variables:
- group: twine
- group: e2e
- group: codecov


stages:
- template: stage-lint.yml
- template: stage-unit.yml
  parameters:
    codecov.token: $(codecov.token)
- template: stage-e2e.yml
  parameters:
    e2e.token: $(e2e.token)
    codecov.token: $(codecov.token)
- stage: deployment
  displayName: "Deploy"
  jobs:
  - job: deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: "User Python 3.7"

    - script: |
        make init
      displayName: 'Install dependencies'

    - script: |
        python setup.py sdist bdist_wheel
      displayName: 'Make dists'

    - script: |
        python -m pip install twine
      displayName: 'Install twine'

    - script: |
        twine upload dist/*
      displayName: 'PyPI upload'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $(twine.token)
      
