stages:
- stage: e2e
  displayName: "E2E"
  jobs:
  - job:
    displayName: " "
    strategy:
      matrix:
        Py36-Linux:
          python.version: '3.6'
          image: 'ubuntu-latest'
        Py37-Linux:
          python.version: '3.7'
          image: 'ubuntu-latest'
        Py36-Win64:
          python.version: '3.6'
          image: 'vs2017-win2016'
        Py37-Win64:
          python.version: '3.7'
          image: 'vs2017-win2016'
        Py36-Mac:
          python.version: '3.6'
          image: 'macos-latest'
        Py37-Mac:
          python.version: '3.7'
          image: 'macos-latest'

    pool:
      vmImage: $[ variables['image'] ]

    timeoutInMinutes: 30

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: "Use Python $(python.version)"

    - script: |
        python -m pip install -U pip wheel
      displayName: 'Install prerequirements'

    - script: |
        pip install -r requirements/ci.txt pytest-azurepipelines
        pip install .
      displayName: 'Install dependencies'

    - script: |
        make e2e
      displayName: 'Run e2e'
      env:
        CLIENT_TEST_E2E_USER_NAME: $(e2e.token)
        PYTEST_XDIST_NUM_THREADS: 8

    - script: |
        pip install codecov
        python -m codecov -f coverage.xml -X gcov
      displayName: 'Upload coverage reports'
      env:
        CODECOV_TOKEN: $(codecov.token)
