name: Dependabot unmerge-on-error
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # pull_request or pull_request_target initiated by dependabot
    if: ${{ github.actor == 'dependabot[bot]' &&
            startsWith(github.event.workflow_run.event, 'pull_request') }}
    steps:
      - name: PR number
        run: echo "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.workflow.pull_requests[0].number }}
      - name: Check statuses
        if: ${{ github.event.workflow.conclusion != 'success' }}
        run: |
          gh pr merge --squash --disable-auto "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.workflow.pull_requests[0].number }}
