name: Dependabot unmerge-on-error
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # pull_request or pull_request_target initiated by dependabot
    if: ${{ github.actor == 'dependabot[bot]' && startsWith("pull_request", github.event.workflow_run.event) }}
    steps:
      - name: Check statuses
        if: ${{ github.event.workflow.conclusion != 'success' }}
        run: |
          gh pr merge --disable-auto "$PR_NUMBER"
        env:
          PR_NUMBER: ${{github.event.workflow.pull_requests[0].number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
